version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mariadb
    command: npm run dev  # Usa nodemon para desarrollo

  frontend-html-css:
    build:
      context: ./frontend-html-css
    ports:
      - '3000:3000'
    volumes:
      - ./frontend-html-css:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ["nodemon", "--config", "nodemon.json"]

  frontend-ant-design:
    build:
      context: ./frontend-ant-design
    ports:
      - '3001:3000'
    volumes:
      - ./frontend-ant-design:/app
      - /app/node_modules
    depends_on:
      - backend

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: uo303984
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./backend/sql:/docker-entrypoint-initdb.d/
    command: --init-file /docker-entrypoint-initdb.d/schema.sql 
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '8080:80'
    depends_on:
      - mariadb

volumes:
  mariadb-data:
